# Generated by Django 3.0.1 on 2021-05-08 05:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=10, unique=True)),
                ('fees', models.FloatField(max_length=60)),
                ('date', models.DateField(default=datetime.date(2021, 5, 8))),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=80, unique=True)),
                ('starting_date', models.DateField(default=datetime.date(2021, 5, 8))),
                ('course_fee', models.FloatField(max_length=50)),
                ('status', models.CharField(choices=[('B', 'yet to Begin'), ('G', 'onGoing'), ('C', 'Completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('counsellor_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('counsellor_name', models.CharField(max_length=120)),
                ('phone_no', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=120, unique=True)),
                ('duration', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(max_length=60)),
                ('payment_date', models.DateField(default=datetime.date(2021, 5, 8))),
                ('payment_status', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Paid')], max_length=1)),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=120)),
                ('phone_no', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=60)),
                ('college_name', models.CharField(max_length=100)),
                ('enquiry_date', models.DateField(default=datetime.date(2021, 5, 8))),
                ('followup_date', models.DateField()),
                ('stud_status', models.IntegerField(choices=[('0', 'Pending'), ('1', 'Admitted'), ('2', 'Cancel')], max_length=1)),
                ('Counsellor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Counsellor')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.CourseModel')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.CourseModel'),
        ),
        migrations.AddField(
            model_name='admission',
            name='batch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Batch'),
        ),
        migrations.AddField(
            model_name='admission',
            name='enquiry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Enquiry'),
        ),
    ]
