# Generated by Django 3.0.1 on 2021-05-11 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 11)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='starting_date',
            field=models.DateField(default=datetime.date(2021, 5, 11)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date(2021, 5, 11)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2021, 5, 11)),
        ),
    ]
