# Generated by Django 3.0.1 on 2021-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20210511_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='stud_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Admitted'), (2, 'Cancel')], max_length=1),
        ),
    ]
